name: CD using reusable action

on:
  workflow_dispatch:
    inputs:
      artifact_name:
        description: 'Artifact file name (e.g., app_package_build14.zip)'
        required: true

jobs:
  deploy:
    uses: princegupta338/common-cd-actions/.github/workflows/reusable-cd.yml@main
    with:
      artifact_name: ${{ inputs.artifact_name }}
      artifactory_path: 'my-repo-local/my-app'         # Adjust per project
      share_path: ${{ secrets.SHARE_PATH }}
      share_user: ${{ secrets.SHARE_USER }}
      share_password: ${{ secrets.SHARE_PASSWORD }}
    secrets:
      jfrog_user: ${{ secrets.JFROG_USER }}
      jfrog_password: ${{ secrets.JFROG_PASSWORD }}
      jfrog_url: ${{ secrets.JFROG_URL }}
