name: Download from JFrog and Deploy to Shared Folder

on:
  workflow_dispatch:
    inputs:
      artifact_name:
        description: 'Enter artifact name (e.g., app_package_20250530_1234_abc123.zip)'
        required: true

jobs:
  deploy:
    runs-on: windows-latest
    env:
      JFROG_USER: ${{ secrets.JFROG_USER }}
      JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
      JFROG_URL: ${{ secrets.JFROG_URL }}

    steps:
      - name: Download artifact from JFrog
        run: |
          $artifactName = "${{ github.event.inputs.artifact_name }}"
          curl -u $env:JFROG_USER:$env:JFROG_PASSWORD -o $artifactName "$env:JFROG_URL/myrepo/$artifactName"

      - name: Copy to Shared Folder
        run: |
          $artifactName = "${{ github.event.inputs.artifact_name }}"
          $destination = "\\\\TargetServer\\DeployFolder"
          Copy-Item -Path $artifactName -Destination $destination -Force
